IMPROVED BM25 APPROACH: 
relevance(q,d) = BM25(q',d) + BM25(q",d)

Importing Corpus from directory

In [1]:
import pandas as pd
import os, glob
folder = "C:\\Users\\ASUS\\AILA Practice\\casedocs"
os.chdir(folder)
files = glob.glob("*.txt") # Makes a list of all files in folder
corpus = []
corpus_dict = {}
for file1 in files:
    with open (file1, 'r') as f:
        document = f.read() # Reads document content into a string
        corpus.append(document)
        corpus_dict[file1] = document

Removing punctuations and stemming using Porter Stemmer and creating tokenized_corpus

In [2]:
new_corpus = corpus.copy()

In [3]:
#Convert text to Lowercase
import nltk
def to_lower(text):
    return ' '.join([w.lower() for w in nltk.word_tokenize(text)])

for doc in new_corpus:
    i = new_corpus.index(doc)
    result = to_lower(doc)
    new_corpus[i] = result
    
#Remove Punctuations
from string import punctuation
def strip_punctuation(s):
    return ''.join(c for c in s if c not in punctuation)

for doc in new_corpus:
    i = new_corpus.index(doc)
    result = strip_punctuation(doc)
    new_corpus[i] = result

#Remove Numbers
import re
for doc in new_corpus:
    i = new_corpus.index(doc)
    result = re.sub(r'\b[\d]+\b', '', doc)
    new_corpus[i] = result

#Remove Stop Words
import nltk
from nltk.corpus import stopwords
stopwords = stopwords.words('english')

tokenized_corpus = [nltk.word_tokenize(doc) for doc in new_corpus]

for doc in tokenized_corpus:
    i = tokenized_corpus.index(doc)
    result = [word for word in tokenized_corpus[i] if word not in stopwords]
    tokenized_corpus[i] = result
    
#Porter Stemmer for stemming
from nltk.stem import PorterStemmer

ps = PorterStemmer()
for docs in tokenized_corpus:
    i = tokenized_corpus.index(docs)
    for words in docs:
        j = tokenized_corpus[i].index(words)
        tokenized_corpus[i][j] = ps.stem(words)

Using rank_bm25 library and running it against tokenized_corpus

In [4]:
from rank_bm25 import BM25Okapi

bm25A = BM25Okapi(tokenized_corpus)

q' = FINDING IDF VALUES FOR QUERY AND EXTRACTING TOP 50%

START....

importing casedocs_idf = casedocs + query

In [5]:
import pandas as pd
import os, glob
folder_idf = "C:\\Users\\ASUS\\AILA Practice\\casedocs_idf"
os.chdir(folder_idf)
files_idf = glob.glob("*.txt") # Makes a list of all files in folder
corpus_idf = []
dict_idf={}
for file1 in files_idf:
    with open (file1, 'r') as f:
        document = f.read() # Reads document content into a string
        corpus_idf.append(document)
        dict_idf[file1] = document

preprocessing it the same way

In [6]:
#Convert text to Lowercase
import nltk
def to_lower(text):
    return ' '.join([w.lower() for w in nltk.word_tokenize(text)])

for doc in corpus_idf:
    i = corpus_idf.index(doc)
    result = to_lower(doc)
    corpus_idf[i] = result
    
#Remove Punctuations
from string import punctuation
def strip_punctuation(s):
    return ''.join(c for c in s if c not in punctuation)

for doc in corpus_idf:
    i = corpus_idf.index(doc)
    result = strip_punctuation(doc)
    corpus_idf[i] = result

#Remove Numbers
import re
for doc in new_corpus:
    i = new_corpus.index(doc)
    result = re.sub(r'\b[\d]+\b', '', doc)
    new_corpus[i] = result

#Remove Stop Words
import nltk
from nltk.corpus import stopwords
stopwords = stopwords.words('english')

tokenized_corpus_idf = [nltk.word_tokenize(doc) for doc in corpus_idf]

for doc in tokenized_corpus_idf:
    i = tokenized_corpus_idf.index(doc)
    result = [word for word in tokenized_corpus_idf[i] if word not in stopwords]
    tokenized_corpus_idf[i] = result
    
#Porter Stemmer for stemming
from nltk.stem import PorterStemmer

ps = PorterStemmer()
for docs in tokenized_corpus_idf:
    i = tokenized_corpus_idf.index(docs)
    for words in docs:
        j = tokenized_corpus_idf[i].index(words)
        tokenized_corpus_idf[i][j] = ps.stem(words)

using tf-idf vectorizer

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer 

def dummy_fun(doc):
    return doc

tfidf_vectorizer=TfidfVectorizer(
    use_idf=True,
    analyzer='word',
    tokenizer=dummy_fun,
    preprocessor=dummy_fun,
    token_pattern=None)

tfidf_vectorizer_vectors=tfidf_vectorizer.fit_transform(tokenized_corpus_idf)

In [8]:
import numpy as np
# function to get unique values 
def unique(list1): 
    x = np.array(list1) 
    return np.unique(x)

list = unique(tokenized_corpus_idf[0])

In [9]:
dict = {}

for words in list:
    if words in tfidf_vectorizer.get_feature_names():
        index = tfidf_vectorizer.get_feature_names().index(words)
        dict[words] = tfidf_vectorizer.idf_[index]
keys = np.fromiter(dict.keys(), dtype='<U7')
vals = np.fromiter(dict.values(), dtype=float)

In [10]:
import math
feature_arr = np.array(keys)
tfidf_sort = np.argsort(vals).flatten()[::-1]

top = len(list)/2
m = math.ceil(top)
top_m = feature_arr[tfidf_sort][:m]
top_m

array(['acd', 'v1', 'anticor', 'patwari', 'gratif', 'trap', 'raid',
       'superan', 'suspens', 'pension', 'therefr', 'meanwhi', 'deputi',
       '1985', 'superin', '1976', '1987', 'represe', 'thereto', '1998',
       '2001', 'age', 'pursuan', 'stood', '2003', 'octob', 'compet',
       'februar', 'januari', 'complai', 'juli', 'singl', 'illeg', 'event',
       'villag', 'lodg', 'servic', 'ask', 'sought', 'acquit', 'commiss',
       'divis', 'reach', 'writ', 'work', 'ie', 'laid', '25', 'prefer'],
      dtype='<U7')

END....

Applying BM25

In [11]:
doc_scores_A = bm25A.get_scores(top_m)
doc_scores_A

array([ 9.58760044,  7.76808593, 11.05586693, ...,  2.83719159,
        8.08823998,  5.35177594])

q" = FINDING SCORES FOR q"

In [12]:
from rank_bm25 import BM25Okapi

bm25B = BM25Okapi(tokenized_corpus)

In [13]:
doc_scores_B = bm25B.get_scores(list)
doc_scores_B

array([ 97.27615437,  97.28302863, 110.61634174, ...,  77.07711737,
        85.1291916 ,  98.46188324])

ADDING SCORES for q' and q" and obtain scores for all casedocs

In [14]:
res_list = [doc_scores_A + doc_scores_B for i in range(len(doc_scores_A))]

In [15]:
res_list = res_list[0]
res_list

array([106.86375481, 105.05111457, 121.67220867, ...,  79.91430897,
        93.21743158, 103.81365918])

SORTING RESULTANT SCORES IN DESCENDING ORDER

In [16]:
top_n = np.argsort(res_list)[::-1]
result = [corpus[i] for i in top_n]

In [17]:
scores = res_list[top_n]
scores

array([190.35056406, 181.80914462, 177.64910465, ...,  30.0382047 ,
        25.76576609,  22.74720282])

In [18]:
output = []

for item in result:
    for filename, content in corpus_dict.items():
        if content == item:
            output.append(filename)

In [19]:
output

['C2644.txt',
 'C2638.txt',
 'C2846.txt',
 'C2628.txt',
 'C2316.txt',
 'C2765.txt',
 'C2462.txt',
 'C2242.txt',
 'C823.txt',
 'C1830.txt',
 'C1623.txt',
 'C2699.txt',
 'C1107.txt',
 'C1234.txt',
 'C2686.txt',
 'C2657.txt',
 'C1837.txt',
 'C2721.txt',
 'C1483.txt',
 'C174.txt',
 'C620.txt',
 'C757.txt',
 'C2311.txt',
 'C13.txt',
 'C1667.txt',
 'C1930.txt',
 'C2517.txt',
 'C764.txt',
 'C1812.txt',
 'C1994.txt',
 'C1682.txt',
 'C236.txt',
 'C1827.txt',
 'C2339.txt',
 'C2665.txt',
 'C1558.txt',
 'C1200.txt',
 'C2313.txt',
 'C162.txt',
 'C1701.txt',
 'C128.txt',
 'C2490.txt',
 'C1304.txt',
 'C1426.txt',
 'C2874.txt',
 'C712.txt',
 'C1907.txt',
 'C1435.txt',
 'C647.txt',
 'C143.txt',
 'C867.txt',
 'C1196.txt',
 'C316.txt',
 'C2355.txt',
 'C605.txt',
 'C958.txt',
 'C993.txt',
 'C2725.txt',
 'C1389.txt',
 'C941.txt',
 'C2642.txt',
 'C348.txt',
 'C2266.txt',
 'C1407.txt',
 'C1050.txt',
 'C1806.txt',
 'C514.txt',
 'C1898.txt',
 'C1887.txt',
 'C914.txt',
 'C1541.txt',
 'C141.txt',
 'C2707.txt',
 

In [20]:
new_output = []
sstring = '.txt'
for item in output:
    if item.endswith(sstring): 
        new_output.append(item[:-(len(sstring))])

In [21]:
new_output

['C2644',
 'C2638',
 'C2846',
 'C2628',
 'C2316',
 'C2765',
 'C2462',
 'C2242',
 'C823',
 'C1830',
 'C1623',
 'C2699',
 'C1107',
 'C1234',
 'C2686',
 'C2657',
 'C1837',
 'C2721',
 'C1483',
 'C174',
 'C620',
 'C757',
 'C2311',
 'C13',
 'C1667',
 'C1930',
 'C2517',
 'C764',
 'C1812',
 'C1994',
 'C1682',
 'C236',
 'C1827',
 'C2339',
 'C2665',
 'C1558',
 'C1200',
 'C2313',
 'C162',
 'C1701',
 'C128',
 'C2490',
 'C1304',
 'C1426',
 'C2874',
 'C712',
 'C1907',
 'C1435',
 'C647',
 'C143',
 'C867',
 'C1196',
 'C316',
 'C2355',
 'C605',
 'C958',
 'C993',
 'C2725',
 'C1389',
 'C941',
 'C2642',
 'C348',
 'C2266',
 'C1407',
 'C1050',
 'C1806',
 'C514',
 'C1898',
 'C1887',
 'C914',
 'C1541',
 'C141',
 'C2707',
 'C172',
 'C1977',
 'C521',
 'C1457',
 'C842',
 'C489',
 'C2318',
 'C1823',
 'C2770',
 'C2895',
 'C242',
 'C186',
 'C2290',
 'C2140',
 'C1725',
 'C334',
 'C2783',
 'C637',
 'C2798',
 'C1901',
 'C2855',
 'C1732',
 'C2445',
 'C994',
 'C30',
 'C1427',
 'C908',
 'C308',
 'C1777',
 'C21',
 'C587',

WRITING TO A FILE FOR TREC-EVAL

In [24]:
f = open("C:\\Users\\ASUS\\AILA Practice\\run-bm25.txt","a")
for i in range(len(corpus)):
    f.write("AILA_Q49 Q0 {} {} {} Default\n".format(new_output[i], (i+1), scores[i]))
f.close()

In [23]:
len(new_output)

2914